version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atualizador_v2
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      # Mapeia a pasta local './database' para a pasta '/app/data' no container
      - ./database:/app/data
      - ./uploads:/app/files
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
