services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: atualizador_v2
    restart: always
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./database:/app/data
      - ./uploads:/app/files
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
